Repository vembrane/vembrane, pull requests merged in 2020-07, with the labels that each got.

#59 Fix github workflow for publishing to PyPI
  .github/workflows/pypi.yml
  pyproject.toml
Labels: maintenance

#60 Replace hardcoded "ANN" in `statistics` with `ann_key`
  vembrane/__init__.py
Labels: bug

#62 Swap expression and VCF input positional arguments, make input default to stdin
  README.md
  vembrane/__init__.py
Labels: minor

#63 Parse info/annotation entries only on dict lookup
  tests/test_vembrane.py
  vembrane/__init__.py
  vembrane/ann_types.py
Labels: enhancement

#65 Swap order of access for FORMAT from `sample → field` to `field → sample`
  README.md
  vembrane/__init__.py
  vembrane/errors.py
Labels: minor

#73 Only allow one ALT allele per record, error if more than one is encountered
  README.md
  vembrane/__init__.py
  vembrane/ann_types.py
  vembrane/errors.py
Labels: minor

#75 Refactor module structure
  pyproject.toml
  tests/test_vembrane.py
  vembrane/__init__.py
  vembrane/ann_types.py
  vembrane/cli.py
  vembrane/globals.py
  vembrane/representations.py
Labels: maintenance

#77 Fix error if there are no INFO/FORMAT entries; add test
  tests/testcases/test11/config.yaml
  tests/testcases/test11/expected.vcf
  tests/testcases/test11/test.vcf
  vembrane/representations.py
Labels: patch
