Repository vembrane/vembrane, pull requests merged in 2022-08, with the labels that each got.

#111 Replace float constants in expressions with IEEE-754-1985 32bit float constants.
  tests/testcases/test_float32/config.yaml
  tests/testcases/test_float32/expected.vcf
  tests/testcases/test_float32/test.vcf
  vembrane/ann_types.py
  vembrane/globals.py
  vembrane/representations.py
Labels: minor

#115 Allow comparisons to `InfoTuple`
  tests/testcases/test_infotuple_comparison/config.yaml
  tests/testcases/test_infotuple_comparison/expected.vcf
  tests/testcases/test_infotuple_comparison/test.vcf
  vembrane/ann_types.py
Labels: patch

#116 Minor formatting/Sort imports
  .pre-commit-config.yaml
  pyproject.toml
  vembrane/ann_types.py
  vembrane/cli.py
  vembrane/common.py
  vembrane/globals.py
  vembrane/modules/annotate.py
  vembrane/modules/filter.py
  vembrane/modules/table.py
  vembrane/representations.py
Labels: maintenance

#117 Make black and isort work together nicely
  .pre-commit-config.yaml
  pyproject.toml
  tests/test_vembrane.py
  vembrane/__init__.py
Labels: maintenance

#119 return NA in case of MISSING (".") ALT
  vembrane/representations.py
Labels: patch

#118 Print the record itself in addition to the record index when encountering exceptions
  vembrane/errors.py
  vembrane/representations.py
Labels: maintenance

#120 `--preserve-order` code restructuring, adding support for BNDs without "EVENTS" but with "MATEID"
  tests/testcases/test_breakend_constellations/config.yaml
  tests/testcases/test_breakend_constellations/expected.vcf
  tests/testcases/test_breakend_constellations/test.vcf
  tests/testcases/test_breakend_constellations_preserve_order/config.yaml
  tests/testcases/test_breakend_constellations_preserve_order/expected.vcf
  tests/testcases/test_breakend_constellations_preserve_order/test.vcf
  tests/testcases/test_mate_pairs/config.yaml
  tests/testcases/test_mate_pairs/expected.vcf
  tests/testcases/test_mate_pairs/test.vcf
  tests/testcases/test_mate_pairs_preserve_order/config.yaml
  tests/testcases/test_mate_pairs_preserve_order/expected.vcf
  tests/testcases/test_mate_pairs_preserve_order/test.vcf
  vembrane/common.py
  vembrane/modules/filter.py
Labels: minor

#125 Explicitly clear builtins in Environment
  vembrane/globals.py
  vembrane/representations.py
Labels: patch
